# Site settings
title: Zvezda
email: ankitpanda1014@gmail.com
# description: "Computer Vision $\cap$ Computer Graphics $\cap$ Mathematics"
baseurl: ""
url: "http://sudoankit.github.io"
twitter_username: sudoankit
github_username:  sudoankit


future: true

plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

